# Generated by Django 3.2.7 on 2021-11-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211118_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='abb_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='full_name',
            field=models.TextField(null=True),
        ),
    ]
